version: "3.9"

services:
  db:
    image: postgres:16
    container_name: dscyclo_2026_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bike_repair_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: dscyclo_2026_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bike_repair_db
    depends_on:
      - db

volumes:
  postgres_data: